### ISSUE TITLE
Tree node v-popper tool-tip text is black on black

### ISSUE THREAD

**Issue by sheriffderek** [formkit/docs-content#105]
I see that this repo is just the docs markdown, but I can't seem to find where this component would live - or how these fit in (otherwise I'd go try and fix it)
<img width="642" alt="CleanShot 2023-09-06 at 13 53 47@2x" src="https://github.com/formkit/docs-content/assets/2066617/e61d8b16-daca-4fed-b39a-a397d0da5954">

**Comment by sheriffderek** [comment]
<img width="557" alt="CleanShot 2023-09-06 at 14 01 46@2x" src="https://github.com/formkit/docs-content/assets/2066617/fd96016a-7567-4f0b-97b7-d2008639881f">

**Comment by GustavoFenilli** [comment]
The website is closed source, we already saw that problem and we are working on fixing it as soon as possible.

**Comment by justin-schroeder** [comment]
We removed prism in favor of monaco on the playground and we missed that it was being used here. Pushing a quickfix to at least make it visible for now.

**Comment by sheriffderek** [comment]
Gotcha! I think a little note in the README about how the docs website is a different closed-source code base would have 1) saved me from digging around looking for it as much - and then also a suggestion on where you'd like comments like this would be helpful for future people trying to help point out bug like that one. : )
