### ISSUE TITLE
The @tailwindcss/forms plugin "breaks" the FormKit Tailwind Genesis theme

### ISSUE THREAD

**Issue by js-modernary** [formkit/docs-content#106]
You may want to specify in the docs (https://formkit.com/essentials/styling) that using the @tailwindcss/forms plugin in combination with the @formkit/themes/tailwindcss plugin and the provided Tailwind version of the Genesis theme will result in a jumbled mess on some elements. (e.g. Select or Autocomplete when using the `selection-appearance="option"` prop).

During pre-release I chalked this up to the shifting recommendations with respect to themes and possible mistakes on my part when generating the Tailwind version of the Genesis theme. Now that you're in v1.0.0 I finally took the time to dig into this further and found the conflict.

Thanks for all of the brilliant work on the project and for your responsiveness on Discord!

**Comment by GustavoFenilli** [comment]
Yeh that is probably the case we should add that it would break the styles as `@tailwindcss/forms` does add styles to forms, or we could take a look and make it work if both are set.
