### ISSUE TITLE
Custom input guide seems to be broken on the website

### ISSUE THREAD

**Issue by dnlsndr** [formkit/docs-content#14]
The custom input guide does not render on the website. I'm using the latest version of chromium and the console does not log any error. If you wish, I can create a PR.

**Comment by justin-schroeder** [comment]
Our vercel build process seems to be occasionally leaving out entire pages. Not sure what is up with that but @andrew-boyd noticed this too. We'll look to get this permanently fixed, but in the meantime that page is back up again at least.
