### ISSUE TITLE
Examples of validation custom rules are no longer available.

### ISSUE THREAD

**Issue by JabhimanyuS** [formkit/docs-content#145]
URL:

[https://formkit.com/essentials/validation#custom-rules](url)

**Comment by fenilli** [comment]
Seens like it was remove in the last update: https://github.com/formkit/docs-content/commit/215d421a16d2ec924bd80b62bf66740e84be64f7

@justin-schroeder

**Comment by JabhimanyuS** [comment]
Could you please add this back to the documentation site? @justin-schroeder 


Thanks.

**Comment by justin-schroeder** [comment]
haha, wth, how did that happen

**Comment by justin-schroeder** [comment]
I have no idea how that happened, stray delete press I suppose. pushing a fix now. thanks!
