### ISSUE TITLE
Tailwindcss playground relative path

### ISSUE THREAD

**Issue by GustavoFenilli** [formkit/docs-content#22]
It seens playground does not work with the new @formkit/tailwindcss import.
It breaks every playground when used, and inside the docs too https://formkit.com/guides/create-a-tailwind-theme#our-first-tailwind-input

**Comment by andrew-boyd** [comment]
@GustavoFenilli is the `tailwind/plugin` and the `@formkit/tailwindcss` in your import map? That import map data is stored in the URL for a playground so it’ll need to be added. You can copy and paste the import map from a new playground to test.

**Comment by GustavoFenilli** [comment]
I think those maps weren't added to the playground yet, as those are not present in a new playground nor at the playgrounds used in the docs.
