### ISSUE TITLE
Auto-animate plugin link is wrong

### ISSUE THREAD

**Issue by AdrianoCahete** [formkit/docs-content#48]
When you go to Get Started, then in the sidebar and click on "[Plugins > AutoAnimate](https://formkit.com/plugins/auto-animate)", the page returns a "Something went wrong" instead of showing the plugin info.

**Comment by justin-schroeder** [comment]
Thanks for the report. 🤔 I seem to be unable to replicate the this issue though

**Comment by AdrianoCahete** [comment]
For some reason, now is working... :O
