### ISSUE TITLE
prev-label props for multiStep form should be name previous-label

### ISSUE THREAD

**Issue by thriist** [formkit/docs-content#83]
Hi there, 
In the doc (https://github.com/formkit/docs-content/blob/master/plugins/multi-step.md), to customise the label of the previous button of a multiStep form the props is named prev-label. 

As i tried to use it, i notice that in "packages/addons/src/plugins/multiStep/sections/stepPrevious.ts" the props name is "previous-label"

that's it, i can make the PR if you want but it would be my first on a public rep and it is a bit scarry ^^'

Regards

**Comment by andrew-boyd** [comment]
Go for it! Will happily merge a PR for this.

**Comment by thriist** [comment]
#84

**Comment by thriist** [comment]
close #84
